[tool.ruff]
line-length = 100
target-version = "py310"
extend-select = ["I", "E", "F", "W", "B", "UP"]
ignore = ["E203", "W503"]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
line-ending = "lf"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
disallow_untyped_defs = true
no_implicit_optional = true
check_untyped_defs = true
pretty = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = [
  "tests",
]
python_files = ["test_*.py", "*_test.py"]
python_functions = ["test_*"]
