analysis:
  albedo:
    modis_products:
    - MOD09GA
    - MOD10A1
    - MCD43A3
    quality_filters:
      cloud_threshold: 0.2
      snow_threshold: 0.1
      outlier_threshold: 2.5
  statistics:
    metrics:
    - rmse
    - bias
    - correlation
    - mae
    confidence_level: 0.95
  spatial:
    pixel_size: 500
    buffer_distance: 1000
data:
  base_path: data
  modis_path: data/modis
  athabasca_modis_path: data/modis/athabasca
  haig_modis_path: data/modis/haig
  coropuna_modis_path: data/modis/coropuna
  aws_path: data/aws
  athabasca_aws_path: data/aws
  haig_aws_path: data/aws
  coropuna_aws_path: data/aws
  glacier_masks_path: data/glacier_masks
output:
  base_path: outputs
  results_path: outputs/results
  plots_path: outputs/plots
  maps_path: outputs/maps
visualization:
  style: seaborn-v0_8
  dpi: 300
  figure_size:
  - 10
  - 8
  colors:
    MOD09GA: '#1f77b4'
    MOD10A1: '#ff7f0e'
    MCD43A3: '#2ca02c'
    AWS: '#d62728'
  plot_output:
    plot_mode: original
    individual_plots: true
    dashboard_plot: true
    eliminate_redundancy: true
    include_outlier_analysis: true
    include_seasonal_analysis: true
    include_distribution_analysis: true
    include_method_comparison: true
    include_temporal_overview: true
    include_statistical_summary: true
    dashboard_panels: 6
    dashboard_size:
    - 18
    - 12
    max_plots_per_glacier: 10
processing:
  parallel: true
  n_cores: -1
  chunk_size: 1000
  memory_limit: 8GB
logging:
  level: INFO
  file: albedo_analysis.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
